version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  snyk: snyk/snyk@1.4.0

jobs:
  SAST:
    parameters:
      fail_if_vul:
        type: boolean
        default: false
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - snyk/install
      - run:
          command: snyk version
          name: Which version of snyk is installed
      - run:
          name: Run code scan
          command: |
             snyk code test --severity-threshold=high --org=vigneshs1017 --project-name="${CIRCLE_PROJECT_REPONAME}" --sarif || STATUS=$?
             if [ "<<parameters.fail_if_vul>>" = "true" ] && [ "$STATUS" -ne 0 ]; then
               echo "Build failed due to vulnerabilities"
               exit 1
             else
               echo "Build continues despite vulnerabilities"
             fi

  scan_application:
    parameters:
      fail_if_vul:
        type: boolean
        default: false
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - snyk/scan:
          token-variable: SNYK_TOKEN
          severity-threshold: high
          fail-on-issues: << parameters.fail_if_vul >>
          project: ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-Dependencies
          monitor-on-build: true
          additional-arguments: "--org=vigneshs1017 --print-deps --detection-depth=10 --prune-repeated-subdependencies"

  scan_build_docker_image:
    parameters:
      fail_if_vul:
        type: boolean
        default: false
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-image:
          ecr-login: true
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: $AWS_ECR_REPO
          tag: $CIRCLE_BRANCH-<< pipeline.number >>
      - snyk/scan:
          docker-image-name: $AWS_ECR_ACCOUNT_URL/$AWS_ECR_REPO:$CIRCLE_BRANCH-<< pipeline.number >>
          fail-on-issues: << parameters.fail_if_vul >>
          monitor-on-build: true
          severity-threshold: high
          target-file: Dockerfile
          project: ${CIRCLE_PROJECT_REPONAME}-Docker
          additional-arguments: "--org=vigneshs1017"
      - aws-ecr/push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: $AWS_ECR_REPO
          tag: $CIRCLE_BRANCH-<< pipeline.number >>

workflows:
  DevSecOps:
    jobs:
      - SAST:
          name: SAST-Development
          fail_if_vul: false
          filters:
            branches:
              only:
                - acc
                - dev
            tags:
              ignore:
                - /v\d+\.\d+\.\d+$/
      - SAST:
          name: SAST-Pre-production
          fail_if_vul: true
          filters:
            branches:
              only:
                - stage
                - acc
                - main
                - prod
            tags:
              ignore:
                - /v\d+\.\d+\.\d+$/
      - scan_application:
          name: Application-Dependencies-Scan-Pre-Prods
          fail_if_vul: true
          filters:
            branches:
              only:
                - stage
                - acc
                - main
                - prod
            tags:
              ignore:
                - /v\d+\.\d+\.\d+$/
          requires:
             - SAST-Pre-production
      - scan_application:
          name: Application-Dependencies-Scan-Development
          fail_if_vul: false
          filters:
            branches:
              only:
                - dev
            tags:
              ignore:
                - /v\d+\.\d+\.\d+$/
          requires:
             - SAST-Development
      - scan_build_docker_image:
          name: Image-Scan-Development
          fail_if_vul: false
          filters:
            branches:
              only:
                - dev
            tags:
              ignore:
                - /v\d+\.\d+\.\d+$/
          requires:
            - Application-Dependencies-Scan-Development
            - SAST-Development
      - scan_build_docker_image:
          name: Image-Scan-Pre-Prod/Production
          fail_if_vul: true
          filters:
            branches:
              only:
                - stage
                - acc
                - main
                - prod
            tags:
              ignore:
                - /v\d+\.\d+\.\d+$/
          requires:
            - Application-Dependencies-Scan-Pre-Prods
            - SAST-Pre-production
